{% set name = "cssbeautifier" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cssbeautifier-{{ version }}.tar.gz
  sha256: 9f7064362aedd559c55eeecf6b6bed65e05f33488dcbe39044f0403c26e1c006

build:
  entry_points:
    - css-beautify = cssbeautifier:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pytest
    - pip
  run:
    - python >={{ python_min }},<4.0
    - jsbeautifier
    - six >=1.13.0
    - editorconfig >=0.12.2

test:
  imports:
    - cssbeautifier
  commands:
    - pip check
    - css-beautify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://beautifier.io
  dev_url: https://github.com/beautify-web/js-beautify
  summary: CSS unobfuscator and beautifier.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
