{% set name = "cssbeautifier" %}
{% set version = "1.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cssbeautifier-{{ version }}.tar.gz
  sha256: 406b04d09e7d62c0be084fbfa2cba5126fe37359ea0d8d9f7b963a6354fc8303

build:
  entry_points:
    - css-beautify = cssbeautifier:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - jsbeautifier
    - six >=1.13.0
    - editorconfig >=0.12.2

test:
  imports:
    - cssbeautifier
  commands:
    - pip check
    - css-beautify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://beautifier.io
  dev_url: https://github.com/beautify-web/js-beautify
  summary: CSS unobfuscator and beautifier.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
